### ISSUE TITLE
Todo items for integrating uax14_rs into icu4x

### ISSUE THREAD

**Issue by aethanyc** [aethanyc/icu4x#1]
I'm planning to use **segmenter** branch as our main branch to integrate uax14_rs into it. It should be the branch that we send the PR to icu4x. **master** branch will keep in sync with icu4x's master branch.

- [x] Remove the platform API calls so that we don't introduce extra crate dependencies into icu4x.
- [ ] (optional) Use getter function to query the line break property value from a codepoint https://github.com/unicode-org/icu4x/pull/448
- [ ] (optional) Use Rust instead of python to generate line break rules into tables. It's good to get rid of the dependency of Python, but it can be done after segmenter is merged into icu4x.

cc @makotokato @zbraniecki @jfkthame

**Comment by makotokato** [comment]
Done for removing Platform API.

**Comment by aethanyc** [comment]
We may have to re-import uax14_rs since uax14_rs got new commits.

**Comment by aethanyc** [comment]
Because the segmenter branch is outdated, so I decided to leave it unchanged. I've porting the commits @makotokato added in segmenter branch back to uax14_rs. Also, @makotokato is continue improving uax14_rs, so the development is better do in the uax14_rs rather than in this repo. 

I start a new branch [`line-breaker-prototype`](https://github.com/aethanyc/icu4x/commits/line-breaker-prototype) for the import. (Note it's intended for the review in https://github.com/unicode-org/icu4x/pull/717, so the commits may be force-pushed and reordered.)

I'm trying to make the branch contain less commits as possible. It should contain only commits that make uax14_rs build and conform to the icu4x coding style, such as renaming, adding needed license header, tweaking path to LTSM data, etc. In the meantime, I'll open issues or PRs in uax14_rs to make the transition easier.

**Comment by aethanyc** [comment]
https://github.com/unicode-org/icu4x/pull/717 is ready for the review. Let's discuss there.
